USE DATABASE SYNTHEA_HEALTHCARE;
USE SCHEMA RAW;

SELECT 'PATIENTS' AS table_name, COUNT(*) AS row_count FROM PATIENTS
UNION ALL
SELECT 'ENCOUNTERS', COUNT(*) FROM ENCOUNTERS
UNION ALL
SELECT 'CONDITIONS', COUNT(*) FROM CONDITIONS
UNION ALL
SELECT 'MEDICATIONS', COUNT(*) FROM MEDICATIONS
UNION ALL
SELECT 'PROCEDURES', COUNT(*) FROM PROCEDURES
UNION ALL
SELECT 'OBSERVATIONS', COUNT(*) FROM OBSERVATIONS;