USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS SYNTHEA_HEALTHCARE;

CREATE SCHEMA IF NOT EXISTS SYNTHEA_HEALTHCARE.RAW;
CREATE SCHEMA IF NOT EXISTS SYNTHEA_HEALTHCARE.STAGING;
CREATE SCHEMA IF NOT EXISTS SYNTHEA_HEALTHCARE.MART;

CREATE STAGE IF NOT EXISTS SYNTHEA_HEALTHCARE.RAW.CSV_STAGE;

CREATE FILE FORMAT IF NOT EXISTS SYNTHEA_HEALTHCARE.RAW.CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('', 'NULL', 'null')
EMPTY_FIELD_AS_NULL = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

USE DATABASE SYNTHEA_HEALTHCARE;
USE SCHEMA RAW;