USE DATABASE SYNTHEA_HEALTHCARE;
USE SCHEMA STAGING;

CREATE OR REPLACE VIEW STAGING.STG_PATIENTS AS
SELECT
    "ID" AS PATIENT_ID,
    TRY_TO_DATE("BIRTHDATE") AS BIRTH_DATE,
    TRY_TO_DATE("DEATHDATE") AS DEATH_DATE,
    "FIRST" AS FIRST_NAME,
    "LAST" AS LAST_NAME,
    "MARITAL" AS MARITAL_STATUS,
    "RACE" AS RACE,
    "ETHNICITY" AS ETHNICITY,
    "GENDER" AS GENDER,
    "CITY" AS CITY,
    "STATE" AS STATE,
    "COUNTY" AS COUNTY,
    "ZIP" AS ZIP_CODE,
    TRY_TO_DECIMAL("LAT", 10, 6) AS LATITUDE,
    TRY_TO_DECIMAL("LON", 10, 6) AS LONGITUDE,
    TRY_TO_DECIMAL("HEALTHCARE_EXPENSES", 12, 2) AS HEALTHCARE_EXPENSES,
    TRY_TO_DECIMAL("HEALTHCARE_COVERAGE", 12, 2) AS HEALTHCARE_COVERAGE,
    FLOOR(DATEDIFF('day', TRY_TO_DATE("BIRTHDATE"), CURRENT_DATE()) / 365.25) AS AGE
FROM RAW.PATIENTS;


CREATE OR REPLACE VIEW STAGING.STG_ENCOUNTERS AS
SELECT
    "ID" AS ENCOUNTER_ID,
    TRY_TO_TIMESTAMP_NTZ("START") AS START_TS,
    TRY_TO_TIMESTAMP_NTZ("STOP") AS STOP_TS,
    "PATIENT" AS PATIENT_ID,
    "ORGANIZATION" AS ORGANIZATION_ID,
    "PROVIDER" AS PROVIDER_ID,
    "PAYER" AS PAYER_ID,
    "ENCOUNTERCLASS" AS ENCOUNTER_CLASS,
    "CODE" AS ENCOUNTER_CODE,
    "DESCRIPTION" AS ENCOUNTER_DESCRIPTION,
    TRY_TO_DECIMAL("BASE_ENCOUNTER_COST", 12, 2) AS BASE_ENCOUNTER_COST,
    TRY_TO_DECIMAL("TOTAL_CLAIM_COST", 12, 2) AS TOTAL_CLAIM_COST,
    TRY_TO_DECIMAL("PAYER_COVERAGE", 12, 2) AS PAYER_COVERAGE,
    "REASONCODE" AS REASON_CODE,
    "REASONDESCRIPTION" AS REASON_DESCRIPTION
FROM RAW.ENCOUNTERS;


CREATE OR REPLACE VIEW STAGING.STG_CONDITIONS AS
SELECT
    TRY_TO_DATE("START") AS START_DATE,
    TRY_TO_DATE("STOP") AS STOP_DATE,
    "PATIENT" AS PATIENT_ID,
    "ENCOUNTER" AS ENCOUNTER_ID,
    "CODE" AS CONDITION_CODE,
    "DESCRIPTION" AS CONDITION_DESCRIPTION
FROM RAW.CONDITIONS;


CREATE OR REPLACE VIEW STAGING.STG_MEDICATIONS AS
SELECT
    TRY_TO_DATE("START") AS START_DATE,
    TRY_TO_DATE("STOP") AS STOP_DATE,
    "PATIENT" AS PATIENT_ID,
    "PAYER" AS PAYER_ID,
    "ENCOUNTER" AS ENCOUNTER_ID,
    "CODE" AS MEDICATION_CODE,
    "DESCRIPTION" AS MEDICATION_DESCRIPTION,
    TRY_TO_DECIMAL("BASE_COST", 12, 2) AS BASE_COST,
    TRY_TO_DECIMAL("PAYER_COVERAGE", 12, 2) AS PAYER_COVERAGE,
    TRY_TO_NUMBER("DISPENSES") AS DISPENSES,
    TRY_TO_DECIMAL("TOTALCOST", 12, 2) AS TOTAL_COST,
    "REASONCODE" AS REASON_CODE,
    "REASONDESCRIPTION" AS REASON_DESCRIPTION
FROM RAW.MEDICATIONS;


CREATE OR REPLACE VIEW STAGING.STG_PROCEDURES AS
SELECT
    TRY_TO_DATE("START") AS START_DATE,
    TRY_TO_DATE("STOP") AS STOP_DATE,
    "PATIENT" AS PATIENT_ID,
    "ENCOUNTER" AS ENCOUNTER_ID,
    "CODE" AS PROCEDURE_CODE,
    "DESCRIPTION" AS PROCEDURE_DESCRIPTION,
    TRY_TO_DECIMAL("BASE_COST", 12, 2) AS BASE_COST,
    "REASONCODE" AS REASON_CODE,
    "REASONDESCRIPTION" AS REASON_DESCRIPTION
FROM RAW.PROCEDURES;


CREATE OR REPLACE VIEW STAGING.STG_OBSERVATIONS AS
SELECT
    TRY_TO_TIMESTAMP_NTZ("DATE") AS OBSERVATION_TS,
    "PATIENT" AS PATIENT_ID,
    "ENCOUNTER" AS ENCOUNTER_ID,
    "CATEGORY" AS OBSERVATION_CATEGORY,
    "CODE" AS OBSERVATION_CODE,
    "DESCRIPTION" AS OBSERVATION_DESCRIPTION,
    "VALUE" AS OBSERVATION_VALUE,
    "UNITS" AS OBSERVATION_UNITS,
    "TYPE" AS OBSERVATION_TYPE
FROM RAW.OBSERVATIONS;