USE DATABASE SYNTHEA_HEALTHCARE;
USE SCHEMA MART;

CREATE OR REPLACE TABLE MART.DIM_PATIENT AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PATIENT_ID) AS PATIENT_KEY,
    PATIENT_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    BIRTH_DATE,
    DEATH_DATE,
    AGE,
    CASE
        WHEN AGE < 18 THEN '0-17'
        WHEN AGE BETWEEN 18 AND 34 THEN '18-34'
        WHEN AGE BETWEEN 35 AND 64 THEN '35-64'
        ELSE '65+'
    END AS AGE_GROUP,
    MARITAL_STATUS,
    RACE,
    ETHNICITY,
    CITY,
    STATE,
    COUNTY,
    ZIP_CODE,
    HEALTHCARE_EXPENSES,
    HEALTHCARE_COVERAGE
FROM STAGING.STG_PATIENTS;


CREATE OR REPLACE TABLE MART.DIM_DATE AS
WITH DATE_VALUES AS (
    SELECT CAST(START_TS AS DATE) AS DATE_DAY
    FROM STAGING.STG_ENCOUNTERS
    WHERE START_TS IS NOT NULL

    UNION

    SELECT START_DATE AS DATE_DAY
    FROM STAGING.STG_CONDITIONS
    WHERE START_DATE IS NOT NULL

    UNION

    SELECT START_DATE AS DATE_DAY
    FROM STAGING.STG_MEDICATIONS
    WHERE START_DATE IS NOT NULL

    UNION

    SELECT START_DATE AS DATE_DAY
    FROM STAGING.STG_PROCEDURES
    WHERE START_DATE IS NOT NULL

    UNION

    SELECT CAST(OBSERVATION_TS AS DATE) AS DATE_DAY
    FROM STAGING.STG_OBSERVATIONS
    WHERE OBSERVATION_TS IS NOT NULL
)
SELECT
    TO_NUMBER(TO_CHAR(DATE_DAY, 'YYYYMMDD')) AS DATE_KEY,
    DATE_DAY,
    YEAR(DATE_DAY) AS YEAR,
    MONTH(DATE_DAY) AS MONTH,
    MONTHNAME(DATE_DAY) AS MONTH_NAME,
    QUARTER(DATE_DAY) AS QUARTER,
    DAY(DATE_DAY) AS DAY_OF_MONTH,
    DAYOFWEEK(DATE_DAY) AS DAY_OF_WEEK
FROM DATE_VALUES;


CREATE OR REPLACE TABLE MART.DIM_CONDITION AS
SELECT
    ROW_NUMBER() OVER (ORDER BY CONDITION_CODE, CONDITION_DESCRIPTION) AS CONDITION_KEY,
    CONDITION_CODE,
    CONDITION_DESCRIPTION
FROM (
    SELECT DISTINCT
        CONDITION_CODE,
        CONDITION_DESCRIPTION
    FROM STAGING.STG_CONDITIONS
    WHERE CONDITION_CODE IS NOT NULL
);


CREATE OR REPLACE TABLE MART.DIM_MEDICATION AS
SELECT
    ROW_NUMBER() OVER (ORDER BY MEDICATION_CODE, MEDICATION_DESCRIPTION) AS MEDICATION_KEY,
    MEDICATION_CODE,
    MEDICATION_DESCRIPTION
FROM (
    SELECT DISTINCT
        MEDICATION_CODE,
        MEDICATION_DESCRIPTION
    FROM STAGING.STG_MEDICATIONS
    WHERE MEDICATION_CODE IS NOT NULL
);


CREATE OR REPLACE TABLE MART.DIM_PROCEDURE AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PROCEDURE_CODE, PROCEDURE_DESCRIPTION) AS PROCEDURE_KEY,
    PROCEDURE_CODE,
    PROCEDURE_DESCRIPTION
FROM (
    SELECT DISTINCT
        PROCEDURE_CODE,
        PROCEDURE_DESCRIPTION
    FROM STAGING.STG_PROCEDURES
    WHERE PROCEDURE_CODE IS NOT NULL
);


CREATE OR REPLACE TABLE MART.FACT_ENCOUNTER AS
SELECT
    ROW_NUMBER() OVER (ORDER BY E.ENCOUNTER_ID) AS ENCOUNTER_FACT_KEY,
    E.ENCOUNTER_ID,
    P.PATIENT_KEY,
    D.DATE_KEY AS START_DATE_KEY,
    E.START_TS,
    E.STOP_TS,
    E.ENCOUNTER_CLASS,
    E.ENCOUNTER_CODE,
    E.ENCOUNTER_DESCRIPTION,
    E.BASE_ENCOUNTER_COST,
    E.TOTAL_CLAIM_COST,
    E.PAYER_COVERAGE,
    E.REASON_CODE,
    E.REASON_DESCRIPTION
FROM STAGING.STG_ENCOUNTERS E
LEFT JOIN MART.DIM_PATIENT P
    ON E.PATIENT_ID = P.PATIENT_ID
LEFT JOIN MART.DIM_DATE D
    ON CAST(E.START_TS AS DATE) = D.DATE_DAY;


CREATE OR REPLACE TABLE MART.FACT_CONDITION AS
SELECT
    ROW_NUMBER() OVER (
        ORDER BY C.PATIENT_ID, C.ENCOUNTER_ID, C.CONDITION_CODE, C.START_DATE
    ) AS CONDITION_FACT_KEY,
    P.PATIENT_KEY,
    D.DATE_KEY AS START_DATE_KEY,
    DC.CONDITION_KEY,
    C.ENCOUNTER_ID,
    C.START_DATE,
    C.STOP_DATE
FROM STAGING.STG_CONDITIONS C
LEFT JOIN MART.DIM_PATIENT P
    ON C.PATIENT_ID = P.PATIENT_ID
LEFT JOIN MART.DIM_DATE D
    ON C.START_DATE = D.DATE_DAY
LEFT JOIN MART.DIM_CONDITION DC
    ON C.CONDITION_CODE = DC.CONDITION_CODE
    AND C.CONDITION_DESCRIPTION = DC.CONDITION_DESCRIPTION;


CREATE OR REPLACE TABLE MART.FACT_MEDICATION AS
SELECT
    ROW_NUMBER() OVER (
        ORDER BY M.PATIENT_ID, M.ENCOUNTER_ID, M.MEDICATION_CODE, M.START_DATE
    ) AS MEDICATION_FACT_KEY,
    P.PATIENT_KEY,
    D.DATE_KEY AS START_DATE_KEY,
    DM.MEDICATION_KEY,
    M.ENCOUNTER_ID,
    M.START_DATE,
    M.STOP_DATE,
    M.BASE_COST,
    M.PAYER_COVERAGE,
    M.DISPENSES,
    M.TOTAL_COST,
    M.REASON_CODE,
    M.REASON_DESCRIPTION
FROM STAGING.STG_MEDICATIONS M
LEFT JOIN MART.DIM_PATIENT P
    ON M.PATIENT_ID = P.PATIENT_ID
LEFT JOIN MART.DIM_DATE D
    ON M.START_DATE = D.DATE_DAY
LEFT JOIN MART.DIM_MEDICATION DM
    ON M.MEDICATION_CODE = DM.MEDICATION_CODE
    AND M.MEDICATION_DESCRIPTION = DM.MEDICATION_DESCRIPTION;


CREATE OR REPLACE TABLE MART.FACT_PROCEDURE AS
SELECT
    ROW_NUMBER() OVER (
        ORDER BY PR.PATIENT_ID, PR.ENCOUNTER_ID, PR.PROCEDURE_CODE, PR.START_DATE
    ) AS PROCEDURE_FACT_KEY,
    P.PATIENT_KEY,
    D.DATE_KEY AS START_DATE_KEY,
    DP.PROCEDURE_KEY,
    PR.ENCOUNTER_ID,
    PR.START_DATE,
    PR.STOP_DATE,
    PR.BASE_COST,
    PR.REASON_CODE,
    PR.REASON_DESCRIPTION
FROM STAGING.STG_PROCEDURES PR
LEFT JOIN MART.DIM_PATIENT P
    ON PR.PATIENT_ID = P.PATIENT_ID
LEFT JOIN MART.DIM_DATE D
    ON PR.START_DATE = D.DATE_DAY
LEFT JOIN MART.DIM_PROCEDURE DP
    ON PR.PROCEDURE_CODE = DP.PROCEDURE_CODE
    AND PR.PROCEDURE_DESCRIPTION = DP.PROCEDURE_DESCRIPTION;