USE DATABASE SYNTHEA_HEALTHCARE;
USE SCHEMA MART;

CREATE OR REPLACE VIEW MART.VW_KPI_OVERVIEW AS
SELECT
    (SELECT COUNT(*) FROM MART.DIM_PATIENT) AS TOTAL_PATIENTS,
    (SELECT COUNT(*) FROM MART.FACT_ENCOUNTER) AS TOTAL_ENCOUNTERS,
    (SELECT COUNT(*) FROM MART.FACT_CONDITION) AS TOTAL_CONDITIONS,
    (SELECT COUNT(*) FROM MART.FACT_MEDICATION) AS TOTAL_MEDICATIONS,
    (SELECT ROUND(AVG(TOTAL_CLAIM_COST), 2) FROM MART.FACT_ENCOUNTER) AS AVG_CLAIM_COST,
    (SELECT ROUND(SUM(TOTAL_CLAIM_COST), 2) FROM MART.FACT_ENCOUNTER) AS TOTAL_CLAIM_COST;


CREATE OR REPLACE VIEW MART.VW_ENCOUNTERS_BY_AGE_GENDER AS
SELECT
    P.AGE_GROUP,
    P.GENDER,
    COUNT(F.ENCOUNTER_FACT_KEY) AS ENCOUNTER_COUNT,
    ROUND(AVG(F.TOTAL_CLAIM_COST), 2) AS AVG_CLAIM_COST
FROM MART.FACT_ENCOUNTER F
JOIN MART.DIM_PATIENT P
    ON F.PATIENT_KEY = P.PATIENT_KEY
GROUP BY
    P.AGE_GROUP,
    P.GENDER;


CREATE OR REPLACE VIEW MART.VW_TOP_CONDITIONS AS
SELECT
    C.CONDITION_DESCRIPTION,
    COUNT(F.CONDITION_FACT_KEY) AS CONDITION_COUNT
FROM MART.FACT_CONDITION F
JOIN MART.DIM_CONDITION C
    ON F.CONDITION_KEY = C.CONDITION_KEY
GROUP BY
    C.CONDITION_DESCRIPTION
ORDER BY CONDITION_COUNT DESC;


CREATE OR REPLACE VIEW MART.VW_TOP_MEDICATIONS AS
SELECT
    M.MEDICATION_DESCRIPTION,
    COUNT(F.MEDICATION_FACT_KEY) AS MEDICATION_COUNT,
    ROUND(SUM(F.TOTAL_COST), 2) AS TOTAL_MEDICATION_COST
FROM MART.FACT_MEDICATION F
JOIN MART.DIM_MEDICATION M
    ON F.MEDICATION_KEY = M.MEDICATION_KEY
GROUP BY
    M.MEDICATION_DESCRIPTION
ORDER BY MEDICATION_COUNT DESC;


CREATE OR REPLACE VIEW MART.VW_ENCOUNTER_TRENDS AS
SELECT
    D.YEAR,
    D.MONTH,
    D.MONTH_NAME,
    COUNT(F.ENCOUNTER_FACT_KEY) AS ENCOUNTER_COUNT,
    ROUND(SUM(F.TOTAL_CLAIM_COST), 2) AS TOTAL_CLAIM_COST,
    ROUND(AVG(F.TOTAL_CLAIM_COST), 2) AS AVG_CLAIM_COST
FROM MART.FACT_ENCOUNTER F
JOIN MART.DIM_DATE D
    ON F.START_DATE_KEY = D.DATE_KEY
GROUP BY
    D.YEAR,
    D.MONTH,
    D.MONTH_NAME
ORDER BY
    D.YEAR,
    D.MONTH;


CREATE OR REPLACE VIEW MART.VW_COST_BY_AGE_GROUP AS
SELECT
    P.AGE_GROUP,
    COUNT(F.ENCOUNTER_FACT_KEY) AS ENCOUNTER_COUNT,
    ROUND(SUM(F.TOTAL_CLAIM_COST), 2) AS TOTAL_CLAIM_COST,
    ROUND(AVG(F.TOTAL_CLAIM_COST), 2) AS AVG_CLAIM_COST
FROM MART.FACT_ENCOUNTER F
JOIN MART.DIM_PATIENT P
    ON F.PATIENT_KEY = P.PATIENT_KEY
GROUP BY
    P.AGE_GROUP
ORDER BY
    P.AGE_GROUP;

SELECT * FROM MART.VW_KPI_OVERVIEW;

SELECT * FROM MART.VW_TOP_CONDITIONS LIMIT 10;

SELECT * FROM MART.VW_ENCOUNTER_TRENDS LIMIT 10;