USE DATABASE SYNTHEA_HEALTHCARE;
USE SCHEMA MART;

SELECT
    P.AGE_GROUP,
    P.GENDER,
    COUNT(F.ENCOUNTER_FACT_KEY) AS ENCOUNTER_COUNT,
    ROUND(AVG(F.TOTAL_CLAIM_COST), 2) AS AVG_CLAIM_COST
FROM MART.FACT_ENCOUNTER F
JOIN MART.DIM_PATIENT P
    ON F.PATIENT_KEY = P.PATIENT_KEY
GROUP BY
    P.AGE_GROUP,
    P.GENDER
ORDER BY
    P.AGE_GROUP,
    P.GENDER;